apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flashcards
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: flashcards-frontend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
# Porta 5173 mantida para o CORS dos backends continuar funcionando
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flashcards
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 80
