spring.application.name=categoria-service
server.port=8081

# H2 (banco em arquivo — persiste entre reinicializações)
spring.datasource.url=jdbc:h2:file:./data/categoriadb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Console H2 (acessar em http://localhost:8081/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# RabbitMQ — broker de eventos (sobe via docker-compose.yml na raiz do repo)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
